python ./scripts/build_demonstrator.py \
    --name "AutoPrognosis: UK Biobank Diabetes study" \
    --model_path=./workspace/biobank_diabetes/model.p \
    --dataset_path=./workspace/biobank_diabetes/biobank_diabetes.csv \
    --time_column=time_to_event \
    --target_column=event \
    --horizons="365, 730, 1095, 1460, 1825, 2190, 2555, 2920, 3285, 3650, 4015, 4380" \
    --task_type=risk_estimation \
    --explainers="invase,kernel_shap" \
    --extras=biobank_diabetes \
    --auth=True
